### ISSUE TITLE
The official import tools has been available!

### ISSUE THREAD

**Issue by 4wheels** [ttencate/sf2github#29]
When I had similar problems migrating projects from SourceForge to GitHub, I found this cool project. However, a better and easier way was successful managed, because of the official tools.

Therefore, **in most cases, this tools is no longer needed, and use the official import tools instead**.

First, go to [the GitHub import tools](http://import.github.com/).
Second, fill your SourceForge url like this:

    git://git.code.sf.net/p/yourproject/code

Finally, finish the rest steps in only seconds.

Notice: you can still use this great tool if you like. What's more, take the license into consideration.

**Comment by ttencate** [comment]
I haven't tried it, but from the documentation, it seems that the Importer Tool only imports source code. sf2github, on the other hand, was made to import issues from SourceForge's issue tracker into GitHub.

**Comment by 4wheels** [comment]
Yes, you are right. If the user only want every commits, he may use the import tools; but if he want to guarantee everything like issue tracker, wiki, etc, he should use your project.
