### ISSUE TITLE
abuse detection mechanism

### ISSUE THREAD

**Issue by ChristianMayer** [ttencate/sf2github#31]
Importing my issues I got this message after quite a few issues were imported:

    403: You have triggered an abuse detection mechanism and have been temporarily blocked from content creation. Please retry your request again later.

How can I avoid that?

**Comment by ttencate** [comment]
See https://github.com/ttencate/sf2github/issues/30 for a possible workaround. Pull requests welcome!

**Comment by codeguru42** [comment]
Let's close this issue as a dupe.
